<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\GomexMVC\Controllers\ArtikalController.cs" Link="Controllers\ArtikalController.cs" />
    <Compile Include="..\GomexMVC\Controllers\DashboardController.cs" Link="Controllers\DashboardController.cs" />
  </ItemGroup>

</Project>
